# Generated by Django 4.1.4 on 2022-12-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('position', models.CharField(choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center')], max_length=2)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('birth_date', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('college', models.CharField(max_length=40)),
            ],
        ),
    ]
