# Generated by Django 4.1.4 on 2022-12-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_player_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.CharField(max_length=2),
        ),
    ]
