# Generated by Django 4.1.2 on 2022-12-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_player_height_alter_player_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
